name: Compile Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - amd64
        vsversion: 
          - 2022
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Enable Developer Command Prompt MSVC
      uses: ilammy/msvc-dev-cmd@v1.11.0

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.211.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Cross, SPIRV-Tools, SPIRV-Reflect, SPIRV-Headers
        vulkan-use-cache: true

    - name: Compile Prerequisites (FMT)
      working-directory: ./3rdParty/fmt/
      run: msbuild fmt.vcxproj
      
    - name: Compile Prerequisites (GLFW3)
      working-directory: ./3rdParty/glfw/src/
      run: msbuild glfw.vcxproj
      
    - name: Compile Prerequisites (RTAUDIO)
      working-directory: ./3rdParty/rtaudio/msvc/
      run: msbuild rtaudio.vcxproj
    
    - name: Compile Prerequisites (WINPTHREADS)
      working-directory: ./3rdParty/winpthreads/
      run: msbuild winpthreads.vcxproj
    
    - name: Compile Prerequisites (ZYDIS)
      working-directory: ./3rdParty/zydis/msvc/
      run: msbuild Zydis.sln
    
    - name: Compile Prerequisites (TINYDBR)
      working-directory: ./3rdParty/tinydbr/
      run: msbuild TinyDBR.vcxproj
      
    - name: Compile GPCS4.
      run: msbuild GPCS4.sln
